import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#d3cfc5',
  },
  listContainer: {
    width: '80%',
    margin: 20,
    justifyContent: 'space-evenly',
  },
  textContainer: {
    width: '90%',
    margin: 20,
  },
  tableContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    width: '90%',
    margin: 20,
  },
  tableText: {
    flex: 1,
    flexBasis: 0,
    fontSize: 20,
    color: '#000',
    fontFamily: 'Raleway_400Regular',
    flexShrink: 1,
  },
  tableHeaders: {
    flex: 1,
    flexBasis: 0,
    fontSize: 20,
    color: '#000',
    fontFamily: 'Raleway_700Bold',
    flexShrink: 1,
  },
  text: {
    fontSize: 25,
    fontFamily: 'Raleway_400Regular',
    color: '#2c2921',
    flexBasis: 1,
  },
  h1: {
    fontSize: 50,
    fontWeight: '500',
    fontFamily: 'Raleway_700Bold',
    color: '#2c2921',
    letterSpacing: -3,
    flexBasis: 1,
    textShadowColor: '#f4f3f0',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 1,
  },
  h2: {
    fontSize: 45,
    fontWeight: '500',
    fontFamily: 'Raleway_700Bold',
    color: '#2c2921',
    letterSpacing: 2,
  },
  h3: {
    fontSize: 35,
    fontWeight: '500',
    fontFamily: 'Raleway_700Bold',
    color: '#2c2921',
  },
  buttonText: {
    fontSize: 25,
    textAlign: 'center',
    fontFamily: 'Raleway_500Medium',
    color: '#2c2921',
    padding: 5,
  },
  button: {
    backgroundColor: '#f4f3f0',
    justifyContent: 'center',
    alignItems: 'center',
    width: '60%',
    borderWidth: 1,
    borderRadius: 10,
    flexWrap: 'wrap',
  },
  tabBarActive: {
    color: '#2c2921',
  },
  tabBarInactive: {
    color: '#665f4d',
  },
  img: {
    width: '100%',
    height: 400,
    marginTop: 260,
    marginBottom: 10,
    borderBottomLeftRadius: 200,
    borderTopLeftRadius: 200,
    position: 'absolute',
    zIndex: -1,
  },
  backgroundImg: {
    borderTopLeftRadius: 200,
    borderTopRightRadius: 200,
    height: 400,
    position: 'relative',
  },
  linkImg: {
    resizeMode: 'cover',
    height: 150,
    width: '90%',
    position: 'absolute',
    borderTopLeftRadius: 50,
    borderBottomLeftRadius: 50,
    borderBottomRightRadius: 50,
    borderWidth: 1,
    borderColor: '#0f0e0b',
  },
  linkImgContainer: {
    marginTop: 70,
    marginBottom: 70,
    alignItems: 'center',
    justifyContent: 'center',
  },
  input: {
    padding: 5,
    marginTop: 10,
    marginBottom: 10,
    width: '80%',
    height: 30,
    borderBottomColor: '#2c2921',
    borderBottomWidth: 2,
  },
  icon: {
    color: '#0f0e0b',
    alignSelf: 'center',
  },
});
