import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#d3cfc5',
  },
  listContainer: {
    width: '80%',
    margin: 20,
    justifyContent: 'space-evenly',
  },
  textContainer: {
    width: '90%',
    margin: 20,
  },
  tableContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    width: '90%',
    margin: 20,
  },
  tableText: {
    flex: 1,
    flexBasis: 0,
    fontSize: 20,
    color: '#000',
    fontFamily: 'JosefinSans_400Regular',
    flexShrink: 1,
  },
  tableHeaders: {
    flex: 1,
    flexBasis: 0,
    fontSize: 20,
    color: '#000',
    fontFamily: 'JosefinSans_700Bold',
    flexShrink: 1,
  },
  text: {
    fontSize: 26,
    fontFamily: 'JosefinSans_400Regular',
    color: '#2c2921',
    flexBasis: 1,
  },
  h1: {
    fontSize: 54,
    fontWeight: '500',
    fontFamily: 'CrimsonText_700Bold',
    color: '#2c2921',
    flexBasis: 1,
    textShadowColor: '#f4f3f0',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 1,
  },
  h2: {
    fontSize: 46,
    fontWeight: '500',
    fontFamily: 'CrimsonText_700Bold',
    color: '#2c2921',
  },
  h3: {
    fontSize: 32,
    fontWeight: '500',
    fontFamily: 'CrimsonText_700Bold',
    color: '#2c2921',
  },
  buttonText: {
    fontSize: 26,
    textAlign: 'center',
    fontFamily: 'JosefinSans_400Regular',
    color: '#2c2921',
    padding: 5,
  },
  button: {
    backgroundColor: '#f4f3f0',
    alignItems: 'center',
    alignContent: 'center',
    width: '60%',
    borderWidth: 1,
    borderRadius: 10,
    flexWrap: 'wrap',
  },
  tabBarActive: {
    color: '#2c2921',
  },
  tabBarInactive: {
    color: '#665f4d',
  },
  backgroundImg: {
    borderTopLeftRadius: 200,
    borderTopRightRadius: 200,
    height: 400,
    position: 'relative',
  },
  listImg: {
    resizeMode: 'cover',
    width: '100%',
    marginBottom: 10,
    height: 250,
    marginLeft: 50,
    borderBottomLeftRadius: 50,
  },
  linkImg: {
    resizeMode: 'cover',
    height: 150,
    width: '90%',
    position: 'absolute',
    borderTopLeftRadius: 50,
    borderBottomLeftRadius: 50,
    borderBottomRightRadius: 50,
    borderWidth: 1,
    borderColor: '#0f0e0b',
  },
  linkImgContainer: {
    marginTop: 70,
    marginBottom: 70,
    alignItems: 'center',
    justifyContent: 'center',
  },
  input: {
    padding: 5,
    marginTop: 10,
    marginBottom: 10,
    width: '80%',
    height: 30,
    borderBottomColor: '#2c2921',
    borderBottomWidth: 2,
  },
  icon: {
    color: '#0f0e0b',
    alignSelf: 'center',
  },
});
